#!/usr/bin/env python3
"""Generate the Wine <-> native-macOS Steamworks bridge from steam_api.json.

The Steamworks SDK ships a machine-readable description of every interface it
exposes.  The bridge is a mechanical transformation of that description, so it
is generated rather than written by hand: 35 interfaces and 925 methods is far
past the point where a hand-maintained wrapper stays correct across an SDK bump.

Both halves of the bridge live in one Wine process and therefore in one address
space, which is the whole reason this design is tractable.  Pointers handed to
us by the PE side stay valid on the Unix side, so nothing has to be marshalled
or copied -- the only thing that actually differs across the boundary is the
calling convention (Microsoft x64 on the PE side, System V on the Unix side).
Each method is bridged by packing its arguments into a plain struct, crossing
with a single __wine_unix_call, and unpacking on the other side.  That converts
an ABI problem into a struct-layout problem, and both compilers agree on the
layout of these PODs.

Outputs (all under generated/):
    bridge_calls.h    call-code enum + one params struct per method (shared)
    pe_thunks.cpp     MS-ABI vtable thunks and the vtables themselves
    pe_flat.cpp       the flat SteamAPI_ISteamX_Y exports
    unix_thunks.cpp   System V dispatch, one entry per call code
    exports.def       the DLL export table
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
DEFAULT_JSON = os.path.join(REPO, "src", "public", "steam", "steam_api.json")
OUT = os.path.join(HERE, "generated")

BANNER = """/* Generated by tools/macos-port/steam-bridge/generate.py -- do not edit.
 * Source: Steamworks SDK steam_api.json ({version}).
 */
"""

# Interfaces the *game* implements and hands to Steam.  Their vtables run the
# wrong way across the boundary (Unix code calling PE code), so they are
# reverse-proxied by hand in unix_main.cpp rather than generated.
RESPONSE_IFACES = {
    "ISteamMatchmakingServerListResponse",
    "ISteamMatchmakingPingResponse",
    "ISteamMatchmakingPlayersResponse",
    "ISteamMatchmakingRulesResponse",
}

# Callback function pointers travel the same wrong way and get the same
# treatment: a hand-written System V trampoline per type.
FNPTR_TYPES = {
    "SteamAPIWarningMessageHook_t",
    "FnSteamNetConnectionStatusChanged",
    "FnSteamNetAuthenticationStatusChanged",
    "FnSteamRelayNetworkStatusChanged",
    "FnSteamNetworkingFakeIPResult",
    "FnSteamNetworkingMessagesSessionRequest",
    "FnSteamNetworkingMessagesSessionFailed",
}

# Return types MSVC hands back through a hidden buffer and mingw-w64 does not.
#
# The MS x64 ABI returns a class of size 1, 2, 4 or 8 in RAX -- but MSVC makes
# an exception for a class with a user-declared constructor and returns it
# through a caller-provided buffer instead, passed as the argument after `this`
# and handed back in RAX. GCC applies only the size rule, so a thunk it compiles
# puts the value in RAX where the game reads a pointer:
#
#     call   *0x10(%rax)          ; ISteamUser::GetSteamID
#     mov    (%rax),%rcx          ; MSVC dereferences what came back
#
# and the client dies on the first call with the SteamID itself as the address.
# CSteamID is the only type in this SDK the two compilers disagree about: every
# other by-value return is either a scalar typedef or larger than 8 bytes, where
# both use the buffer. A new one would have to be added here.
MSVC_MEMORY_RETURN = {"CSteamID"}

# ISteamClient::GetISteamGenericInterface hands back an interface chosen by a
# runtime string.  There is no static type to build a vtable from, so it is not
# bridged; Source never calls it.
UNBRIDGED = {"SteamAPI_ISteamClient_GetISteamGenericInterface"}

# Structs with private members.  A generated field-by-field converter cannot
# touch those, so the pair is written by hand in src/pack_manual.cpp against the
# accessors the SDK provides.
MANUAL_CONVERTERS = {"servernetadr_t", "gameserveritem_t"}

# Structs the shipped headers only forward-declare.  Their helper exports still
# have to exist, so they are generated as stubs.
PE_STUB_STRUCTS = {"SteamDatagramHostedAddress", "SteamNetworkingMessage_t"}

# Structs steam_api.json cannot describe faithfully: some are only
# forward-declared in the shipped headers, the rest hide a union that the JSON
# flattens to its largest member.  They are passed across without conversion,
# which is correct only where the two packings agree.  Source touches none of
# them -- they are Steam Input, Steam Datagram and the networking config API.
OPAQUE_STRUCTS = {
    "SteamDatagramHostedAddress",
    "SteamDatagramGameCoordinatorServerLogin",
    "SteamNetworkingFakeIPResult_t",
    "SteamNetworkingConfigValue_t",
    "InputAnalogActionData_t",
    "SteamInputActionEvent_t",
    # Owned by Steam and freed through a function pointer inside itself, so a
    # converted copy would be the wrong object; it also cannot be constructed
    # outside the SDK.  Reaches the game only through ISteamNetworkingSockets
    # and ISteamNetworkingMessages, neither of which Source 2013 uses.
    "SteamNetworkingMessage_t",
}

# Interfaces steam_api.json describes but the shipped headers only
# forward-declare.  There is no class to call methods on, so they get an entry
# with no vtable and any method handing one back returns NULL.
OPAQUE_IFACES = {"ISteamNetworkingFakeUDPPort"}

# Methods that carry a filesystem path.  Native Steam answers with POSIX paths
# and takes POSIX paths, and the Windows process on the other side of the bridge
# can use neither, so these are translated in the thunk -- see path_convert.cpp.
#
# "out" names buffers the native side fills in; "length" marks a method whose
# return value is the length of that buffer, which changes with the path.
# "in" names paths travelling the other way.
#
# ISteamApps::GetAppInstallDir is the one that decides whether the port works at
# all: the engine resolves |appid_440| in gameinfo.txt through it, so every VPK
# Team Fortress 2 supplies is mounted from whatever it returns.
PATH_PARAMS = {
    ("ISteamApps", "GetAppInstallDir"):
        {"out": [("pchFolder", "cchFolderBufferSize")], "length": True},
    ("ISteamAppList", "GetAppInstallDir"):
        {"out": [("pchDirectory", "cchNameMax")], "length": True},
    ("ISteamUGC", "GetItemInstallInfo"): {"out": [("pchFolder", "cchFolderSize")]},
    ("ISteamUser", "GetUserDataFolder"): {"out": [("pchBuffer", "cubBuffer")]},
    ("ISteamUGC", "SetItemContent"): {"in": ["pszContentFolder"]},
    ("ISteamUGC", "BInitWorkshopForGameServer"): {"in": ["pszFolder"]},
    ("ISteamInput", "SetInputActionManifestFilePath"):
        {"in": ["pchInputActionManifestAbsolutePath"]},
}


def path_params(iface, method):
    return PATH_PARAMS.get((iface["classname"], method["methodname"]), {})


def load(path):
    with open(path) as handle:
        return json.load(handle)


def param_name(param, index):
    name = (param.get("paramname") or "").strip()
    if not name or not re.match(r"^[A-Za-z_]\w*$", name):
        name = "a%d" % index
    return name


def field_type(paramtype):
    """The type a parameter takes inside a params struct.

    References cannot be struct members in the shape we need (we assign to the
    field after the struct is default-constructed), so a `T &` becomes a `T *`
    and both sides add the missing & / * at the call.
    """
    stripped = paramtype.strip()
    if stripped.endswith("&"):
        return stripped[:-1].strip() + " *", True
    return stripped, False


def header_versions(header_dir):
    """Interface version strings as the headers define them.

    steam_api.json leaves version_string empty for a few interfaces -- notably
    ISteamClient, which has no accessor macro to carry one -- but the headers
    always have the constant. Reading it rather than hardcoding it means an SDK
    bump does not need this file edited.
    """
    versions = {}
    if not os.path.isdir(header_dir):
        return versions
    pattern = re.compile(r'^\s*#define\s+(\w+_INTERFACE_VERSION)\s+"([^"]+)"', re.M)
    for name in os.listdir(header_dir):
        if not name.endswith(".h"):
            continue
        with open(os.path.join(header_dir, name), errors="replace") as handle:
            for match in pattern.finditer(handle.read()):
                versions[match.group(1)] = match.group(2)
    return versions


class Generator:
    def __init__(self, api, header_versions=None):
        self.api = api
        self.header_versions = header_versions or {}
        self.interfaces = api["interfaces"]
        self.iface_names = [i["classname"] for i in self.interfaces]
        self.iface_set = set(self.iface_names)
        self.calls = []  # (iface, method) in call-code order

    # ---------------------------------------------------------------- helpers

    def iface_version(self, iface):
        version = iface.get("version_string")
        if version:
            return version
        classname = iface["classname"]
        if classname.startswith("ISteam"):
            key = "STEAM%s_INTERFACE_VERSION" % classname[len("ISteam"):].upper()
            if key in self.header_versions:
                return self.header_versions[key]
        return ""

    def returns_interface(self, method):
        ret = method["returntype"].strip()
        if not ret.endswith("*"):
            return None
        base = ret[:-1].strip()
        return base if base in self.iface_set else None

    def returns_opaque(self, method):
        base = self.returns_interface(method)
        return base is not None and base in OPAQUE_IFACES

    def type_info(self, ctype):
        """Split a C++ type into (base, const, pointer depth, reference).

        Used to decide whether a value crossing the bridge needs its packing
        converted, and how to reach it.
        """
        text = ctype.strip()
        is_const = text.startswith("const ")
        is_ref = text.endswith("&")
        if is_ref:
            text = text[:-1].strip()
        depth = text.count("*")
        base = text.replace("const", "").replace("*", "").strip()
        return base, is_const, depth, is_ref

    def converts(self, ctype):
        """The struct name whose packing has to be converted, if any.

        Only a value or a pointer to a single object is handled.  Arrays and
        pointer-to-pointer are passed through: no method the engine calls takes
        an array of a struct whose two layouts differ.
        """
        base, _, depth, is_ref = self.type_info(ctype)
        if base not in getattr(self, "mirrored", ()):
            return None
        if depth > 1:
            return None
        return base

    def bridge_field_type(self, ctype):
        """The type this parameter takes inside a params struct."""
        base, is_const, depth, is_ref = self.type_info(ctype)
        converting = self.converts(ctype)
        if not converting:
            return field_type(ctype)[0], is_ref
        stars = "*" * (1 if (is_ref or depth) else 0)
        prefix = "const " if is_const else ""
        return ("%sSTEAM_BRIDGE_U(%s) %s" % (prefix, base, stars)).strip(), is_ref

    def bridged_methods(self, iface):
        """Methods that get a generated thunk.

        The four response interfaces are implemented by the game, never by
        Steam, so they have no forward thunks at all.
        """
        if iface["classname"] in RESPONSE_IFACES or iface["classname"] in OPAQUE_IFACES:
            return []
        return iface["methods"]

    # ------------------------------------------------------------ params/ABI

    def collect(self):
        for iface in self.interfaces:
            for method in self.bridged_methods(iface):
                if method["methodname_flat"] in UNBRIDGED:
                    continue
                self.calls.append((iface, method))

    # -------------------------------------------------------------- emitters

    def emit_calls_header(self):
        out = [BANNER.format(version=self.api.get("version", "bundled")),
               "#ifndef STEAM_BRIDGE_CALLS_H",
               "#define STEAM_BRIDGE_CALLS_H",
               "",
               "#include \"bridge_types.h\"",
               "",
               "enum steam_bridge_call",
               "{",
               "    steam_bridge_call_attach = 0,",
               "    steam_bridge_call_detach,",
               "    steam_bridge_call_init,",
               "    steam_bridge_call_shutdown,",
               "    steam_bridge_call_restart_app_if_necessary,",
               "    steam_bridge_call_is_steam_running,",
               "    steam_bridge_call_get_hsteamuser,",
               "    steam_bridge_call_get_hsteampipe,",
               "    steam_bridge_call_create_interface,",
               "    steam_bridge_call_find_user_interface,",
               "    steam_bridge_call_find_gameserver_interface,",
               "    steam_bridge_call_release_user_interface,",
               "    steam_bridge_call_dispatch_run_frame,",
               "    steam_bridge_call_dispatch_next,",
               "    steam_bridge_call_dispatch_free,",
               "    steam_bridge_call_dispatch_get_result,",
               "    steam_bridge_call_gameserver_init,",
               "    steam_bridge_call_gameserver_shutdown,",
               "    steam_bridge_call_gameserver_get_hsteamuser,",
               "    steam_bridge_call_gameserver_get_hsteampipe,",
               "    steam_bridge_call_set_warning_hook,",
               "    steam_bridge_call_get_steam_install_path,",
               "    steam_bridge_call_release_response,",
               ""]

        for iface, method in self.calls:
            out.append("    u_%s," % method["methodname_flat"])

        out += ["    steam_bridge_call_count",
                "};",
                ""]

        for iface, method in self.calls:
            out.append("struct u_%s_params" % method["methodname_flat"])
            out.append("{")
            out.append("    void *linux_side;")
            for index, param in enumerate(method["params"]):
                ctype, _ = self.bridge_field_type(param["paramtype"])
                out.append("    %s %s;" % (ctype, param_name(param, index)))
            ret = method["returntype"].strip()
            if ret != "void":
                converting = self.converts(ret)
                if converting:
                    _, _, depth, _ = self.type_info(ret)
                    out.append("    STEAM_BRIDGE_U(%s) %s_ret;"
                               % (converting, "*" if depth else ""))
                else:
                    out.append("    %s _ret;" % ret)
            out.append("};")
            out.append("")

        out += ["#endif /* STEAM_BRIDGE_CALLS_H */", ""]
        self.write("bridge_calls.h", "\n".join(out))

        # The whole design rests on both compilers laying these structs out
        # identically.  This list lets verify-layout.sh prove it rather than
        # assume it.
        listing = [BANNER.format(version=self.api.get("version", "bundled")),
                   "#ifndef STEAM_BRIDGE_PARAMS_LIST_H",
                   "#define STEAM_BRIDGE_PARAMS_LIST_H",
                   "",
                   "#define STEAM_BRIDGE_PARAMS_LIST(X) \\"]
        for index, (iface, method) in enumerate(self.calls):
            tail = "" if index == len(self.calls) - 1 else " \\"
            listing.append("    X(u_%s_params)%s" % (method["methodname_flat"], tail))
        listing += ["", "#endif /* STEAM_BRIDGE_PARAMS_LIST_H */", ""]
        self.write("params_list.h", "\n".join(listing))

    # -- PE side ------------------------------------------------------------

    def thunk_signature(self, method, name):
        args = ["void *_self"]
        for index, param in enumerate(method["params"]):
            args.append("%s %s" % (param["paramtype"].strip(), param_name(param, index)))
        return "static %s __cdecl %s( %s )" % (method["returntype"].strip(), name,
                                               ", ".join(args))

    def msvc_return_adapter(self, method, name):
        """The MSVC-shaped entry point for a method GCC would return in RAX."""
        ret = method["returntype"].strip()
        args = ["void *_self", "%s *_ret" % ret]
        call = ["_self"]
        for index, param in enumerate(method["params"]):
            pname = param_name(param, index)
            args.append("%s %s" % (param["paramtype"].strip(), pname))
            call.append(pname)
        return ["static %s * __cdecl %s( %s )" % (ret, name, ", ".join(args)),
                "{",
                "    *_ret = thunk_%s( %s );" % (method["methodname_flat"],
                                                 ", ".join(call)),
                "    return _ret;",
                "}",
                ""]

    def emit_pe_thunks(self):
        out = [BANNER.format(version=self.api.get("version", "bundled")),
               "#include \"bridge_pe.h\"",
               ""]

        for iface, method in self.calls:
            flat = method["methodname_flat"]
            name = "thunk_" + flat
            out.append(self.thunk_signature(method, name))
            out.append("{")
            # Value-initialised rather than memset: several params structs
            # hold SDK classes with constructors.
            out.append("    struct u_%s_params params{};" % flat)
            out.append("    params.linux_side = steam_bridge_native( _self );")

            paths = path_params(iface, method)
            path_in = set(paths.get("in", []))

            writeback = []
            for index, param in enumerate(method["params"]):
                pname = param_name(param, index)
                ptype = param["paramtype"].strip()
                _, is_ref = field_type(ptype)
                converting = self.converts(ptype)

                if pname in path_in:
                    out.append("    params.%s = steam_bridge_path_in( %s );" % (pname, pname))
                    continue
                # Response interfaces and callback function pointers are PE
                # objects travelling the other way; they are wrapped on the Unix
                # side, where the System V trampoline has to live anyway.
                if converting:
                    base, is_const, depth, ref = self.type_info(ptype)
                    if not depth and not ref:
                        out.append("    steam_bridge_w2u_%s( &%s, &params.%s );"
                                   % (base, pname, pname))
                    elif ref:
                        out.append("    struct u_%s packed_%s{};" % (base, pname))
                        out.append("    steam_bridge_w2u_%s( &%s, &packed_%s );"
                                   % (base, pname, pname))
                        out.append("    params.%s = &packed_%s;" % (pname, pname))
                        if not is_const:
                            writeback.append("    steam_bridge_u2w_%s( &packed_%s, &%s );"
                                             % (base, pname, pname))
                    else:
                        out.append("    struct u_%s packed_%s{};" % (base, pname))
                        out.append("    if (%s)" % pname)
                        out.append("    {")
                        out.append("        steam_bridge_w2u_%s( %s, &packed_%s );"
                                   % (base, pname, pname))
                        out.append("        params.%s = &packed_%s;" % (pname, pname))
                        out.append("    }")
                        if not is_const:
                            writeback.append("    if (%s) steam_bridge_u2w_%s( &packed_%s, %s );"
                                             % (pname, base, pname, pname))
                elif is_ref:
                    out.append("    params.%s = &%s;" % (pname, pname))
                else:
                    out.append("    params.%s = %s;" % (pname, pname))

            out.append("    STEAM_BRIDGE_CALL( u_%s, &params );" % flat)
            out += writeback

            # A path Steam wrote into the caller's buffer, turned into one the
            # Windows side can open.  Where the method reports the length, the
            # translated length is what it now has to report.
            for pname, size_name in paths.get("out", []):
                if paths.get("length"):
                    # Only when the call succeeded: on failure the buffer is
                    # whatever the caller left in it, not a path.
                    out.append("    if (params._ret)")
                    out.append("    {")
                    out.append("        unsigned int translated = steam_bridge_path_out( "
                               "%s, (unsigned int)%s );" % (pname, size_name))
                    out.append("        if (translated) params._ret = translated;")
                    out.append("    }")
                else:
                    out.append("    if (params._ret) steam_bridge_path_out( "
                               "%s, (unsigned int)%s );" % (pname, size_name))

            ret = method["returntype"].strip()
            converting_ret = self.converts(ret)
            if ret != "void" and converting_ret:
                base, _, depth, _ = self.type_info(ret)
                if depth:
                    # The native object lives in Steam's memory and the caller
                    # treats it as short-lived, so the converted copy is a
                    # per-thread buffer with the same lifetime rules.
                    out.append("    static thread_local %s converted;" % base)
                    out.append("    if (!params._ret) return NULL;")
                    out.append("    steam_bridge_u2w_%s( params._ret, &converted );" % base)
                    out.append("    return &converted;")
                else:
                    out.append("    %s converted;" % base)
                    out.append("    steam_bridge_u2w_%s( &params._ret, &converted );" % base)
                    out.append("    return converted;")
            elif ret != "void":
                wrapped = self.returns_interface(method)
                if wrapped and wrapped in OPAQUE_IFACES:
                    out.append("    steam_bridge_log( \"%s is not bridged\" );" % wrapped)
                    out.append("    return NULL;")
                elif wrapped:
                    out.append("    return (%s)steam_bridge_wrap( steam_bridge_iface_%s, "
                               "params._ret );" % (ret, wrapped))
                else:
                    out.append("    return params._ret;")
            out.append("}")
            out.append("")

            if method["returntype"].strip() in MSVC_MEMORY_RETURN:
                out += self.msvc_return_adapter(method, "msvc_thunk_" + flat)

        # Vtables, in declaration order.  A generated vtable is the whole point
        # of the PE side: MSVC lays an interface out exactly this way, so the
        # game's virtual dispatch lands on our thunk with `this` in RCX.
        for iface in self.interfaces:
            methods = self.bridged_methods(iface)
            if not methods:
                continue
            out.append("static void * const vtable_%s[] =" % iface["classname"])
            out.append("{")
            for method in methods:
                if method["methodname_flat"] in UNBRIDGED:
                    out.append("    (void *)steam_bridge_unbridged, /* %s */"
                               % method["methodname"])
                elif method["returntype"].strip() in MSVC_MEMORY_RETURN:
                    out.append("    (void *)msvc_thunk_%s," % method["methodname_flat"])
                else:
                    out.append("    (void *)thunk_%s," % method["methodname_flat"])
            out.append("};")
            out.append("")

        out.append("const struct steam_bridge_iface_info steam_bridge_ifaces[steam_bridge_iface_count] =")
        out.append("{")
        for iface in self.interfaces:
            methods = self.bridged_methods(iface)
            version = self.iface_version(iface)
            if methods:
                out.append('    { "%s", "%s", vtable_%s, %d },'
                           % (iface["classname"], version, iface["classname"], len(methods)))
            else:
                out.append('    { "%s", "%s", NULL, 0 },' % (iface["classname"], version))
        out.append("};")
        out.append("")

        self.write("pe_thunks.cpp", "\n".join(out))

    def emit_pe_flat(self):
        """The flat exports.

        A caller that uses the flat API already holds one of our proxies, so
        each flat export is just the matching thunk under its public name.  The
        thunks are static, so this file is generated next to them.
        """
        out = [BANNER.format(version=self.api.get("version", "bundled")),
               "#include \"bridge_pe.h\"",
               "#include \"pe_thunks.cpp\"",
               ""]

        for iface, method in self.calls:
            flat = method["methodname_flat"]
            ret_type = method["returntype"].strip()
            memory_return = ret_type in MSVC_MEMORY_RETURN
            args = ["%s *_self" % iface["classname"]]
            if memory_return:
                # The caller is MSVC here too, so the flat export takes the
                # hidden buffer the same way the vtable thunk does.
                args.append("%s *_ret" % ret_type)
            call = ["_self"]
            for index, param in enumerate(method["params"]):
                pname = param_name(param, index)
                ptype = param["paramtype"].strip()
                args.append("%s %s" % (ptype, pname))
                call.append(pname)
            out.append("STEAM_BRIDGE_EXPORT %s%s __cdecl %s( %s )"
                       % (ret_type, " *" if memory_return else "", flat,
                          ", ".join(args)))
            out.append("{")
            if memory_return:
                out.append("    *_ret = thunk_%s( %s );" % (flat, ", ".join(call)))
                out.append("    return _ret;")
            else:
                ret = "" if ret_type == "void" else "return "
                out.append("    %sthunk_%s( %s );" % (ret, flat, ", ".join(call)))
            out.append("}")
            out.append("")

        # Interface accessors.  Each is a named shorthand for the lookup the
        # game would otherwise do through SteamInternal_*.
        for iface in self.interfaces:
            for accessor in iface.get("accessors", []):
                kind = accessor["kind"]
                finder = ("steam_bridge_find_gameserver_interface"
                          if kind == "gameserver" else "steam_bridge_find_user_interface")
                out.append("STEAM_BRIDGE_EXPORT %s * __cdecl %s(void)"
                           % (iface["classname"], accessor["name_flat"]))
                out.append("{")
                out.append('    return (%s *)%s( "%s" );'
                           % (iface["classname"], finder, self.iface_version(iface)))
                out.append("}")
                out.append("")

        self.write("pe_flat.cpp", "\n".join(out))

    # -- Unix side ----------------------------------------------------------

    def emit_unix_thunks(self):
        out = [BANNER.format(version=self.api.get("version", "bundled")),
               "#include \"bridge_unix.h\"",
               ""]

        for iface, method in self.calls:
            flat = method["methodname_flat"]
            out.append("static NTSTATUS unix_%s( void *args )" % flat)
            out.append("{")
            out.append("    struct u_%s_params *params = (struct u_%s_params *)args;"
                       % (flat, flat))

            call_args = []
            for index, param in enumerate(method["params"]):
                pname = param_name(param, index)
                ptype = param["paramtype"].strip()
                base = ptype.replace("const", "").replace("*", "").strip()
                _, is_ref = field_type(ptype)
                if ptype in FNPTR_TYPES:
                    call_args.append("steam_bridge_wrap_%s( params->%s )" % (ptype, pname))
                elif base in RESPONSE_IFACES:
                    call_args.append("steam_bridge_wrap_%s( params->%s )" % (base, pname))
                elif is_ref:
                    call_args.append("*params->%s" % pname)
                else:
                    call_args.append("params->%s" % pname)

            invoke = "((%s *)params->linux_side)->%s( %s )" % (
                iface["classname"], method["methodname"], ", ".join(call_args))
            if method["returntype"].strip() == "void":
                out.append("    %s;" % invoke)
            else:
                out.append("    params->_ret = %s;" % invoke)
            out.append("    return STATUS_SUCCESS;")
            out.append("}")
            out.append("")

        # A macro rather than its own array: unix_main.cpp splices these onto
        # the core entries so there is exactly one __wine_unix_call_funcs, and
        # a static_assert against steam_bridge_call_count catches any drift
        # between the enum and the table at compile time.
        out.append("#define STEAM_BRIDGE_GENERATED_CALLS \\")
        for index, (iface, method) in enumerate(self.calls):
            tail = "" if index == len(self.calls) - 1 else " \\"
            out.append("    unix_%s,%s" % (method["methodname_flat"], tail))
        out.append("")

        self.write("unix_thunks.cpp", "\n".join(out))

    # -- exports ------------------------------------------------------------

    def emit_pe_local(self):
        """Exports that never leave the PE side.

        Two groups.  The SDK's struct helpers (SteamNetworkingIPAddr::SetIPv4
        and friends) operate on a Windows-layout struct the caller already
        owns, so bridging them would mean converting a struct in order to run
        code that does not need Steam at all.  The server-browser response
        interfaces are implemented by the game, so their flat forms are plain
        virtual calls on a PE object.

        Structs the headers only forward-declare get a stub, because the export
        has to exist for the import table to resolve even where the function
        cannot do anything.
        """
        out = [BANNER.format(version=self.api.get("version", "bundled")),
               '#include "bridge_pe.h"',
               "",
               "#include <new>",
               ""]
        names = []

        for entry in self.api.get("structs", []):
            struct = entry["struct"]
            for method in entry.get("methods", []):
                flat = method["methodname_flat"]
                names.append(flat)
                args = ["%s *self" % struct]
                call = []
                for index, param in enumerate(method["params"]):
                    pname = param_name(param, index)
                    args.append("%s %s" % (param["paramtype"].strip(), pname))
                    call.append(pname)
                ret = method["returntype"].strip()
                out.append("STEAM_BRIDGE_EXPORT %s __cdecl %s( %s )"
                           % (ret, flat, ", ".join(args)))
                out.append("{")
                if struct in PE_STUB_STRUCTS:
                    out.append("    (void)self;")
                    for name in call:
                        out.append("    (void)%s;" % name)
                    out.append('    steam_bridge_log( "%s is not available" );' % flat)
                    if ret != "void":
                        out.append("    return (%s)0;" % ret)
                elif method["methodname"] == "Construct":
                    out.append("    new (self) %s();" % struct)
                else:
                    prefix = "" if ret == "void" else "return "
                    out.append("    %sself->%s( %s );"
                               % (prefix, method["methodname"], ", ".join(call)))
                out.append("}")
                out.append("")

        for iface in self.interfaces:
            if iface["classname"] not in RESPONSE_IFACES and iface["classname"] not in OPAQUE_IFACES:
                continue
            stub = iface["classname"] in OPAQUE_IFACES
            for slot, method in enumerate(iface["methods"]):
                flat = method["methodname_flat"]
                names.append(flat)
                args = ["%s *self" % iface["classname"]]
                call = []
                for index, param in enumerate(method["params"]):
                    pname = param_name(param, index)
                    args.append("%s %s" % (param["paramtype"].strip(), pname))
                    call.append(pname)
                ret = method["returntype"].strip()
                out.append("STEAM_BRIDGE_EXPORT %s __cdecl %s( %s )"
                           % (ret, flat, ", ".join(args)))
                out.append("{")
                if stub:
                    out.append("    (void)self;")
                    for name in call:
                        out.append("    (void)%s;" % name)
                    out.append('    steam_bridge_log( "%s is not bridged" );' % flat)
                    if ret != "void":
                        out.append("    return (%s)0;" % ret)
                else:
                    prefix = "" if ret == "void" else "return "
                    out.append("    %sself->%s( %s );"
                               % (prefix, method["methodname"], ", ".join(call)))
                out.append("}")
                out.append("")

        self.write("pe_local.cpp", "\n".join(out))
        return names

    def emit_def(self, core_exports, extra=()):
        names = list(core_exports) + list(extra)
        for iface, method in self.calls:
            names.append(method["methodname_flat"])
        for iface in self.interfaces:
            for accessor in iface.get("accessors", []):
                names.append(accessor["name_flat"])

        seen = []
        known = set()
        for name in names:
            if name not in known:
                known.add(name)
                seen.append(name)

        out = ["LIBRARY steam_api64.dll", "EXPORTS"]
        out += ["    " + name for name in sorted(seen)]
        # A variable, not a function: the linker has to be told so.
        out.append("    g_pSteamClientGameServer DATA")
        out.append("")
        self.write("exports.def", "\n".join(out))
        return seen

    def emit_iface_enum(self):
        out = [BANNER.format(version=self.api.get("version", "bundled")),
               "#ifndef STEAM_BRIDGE_IFACES_H",
               "#define STEAM_BRIDGE_IFACES_H",
               "",
               "enum steam_bridge_iface_id",
               "{"]
        for iface in self.interfaces:
            out.append("    steam_bridge_iface_%s," % iface["classname"])
        out += ["    steam_bridge_iface_count",
                "};",
                "",
                "enum steam_bridge_response_id",
                "{"]
        for name in sorted(RESPONSE_IFACES):
            out.append("    steam_bridge_response_%s," % name)
        out += ["    steam_bridge_response_count",
                "};",
                "",
                "#endif /* STEAM_BRIDGE_IFACES_H */",
                ""]
        self.write("bridge_ifaces.h", "\n".join(out))

    # ------------------------------------------------------------ packing

    def struct_fields(self):
        """Every SDK struct steam_api.json describes, by name."""
        out = {}
        for entry in self.api.get("structs", []) + self.api.get("callback_structs", []):
            if entry["struct"] in OPAQUE_STRUCTS:
                continue
            out[entry["struct"]] = entry
        return out

    @staticmethod
    def split_array(fieldtype):
        match = re.match(r"^(.*?)\s*\[\s*([^\]]+)\s*\]$", fieldtype.strip())
        if match:
            return match.group(1).strip(), match.group(2).strip()
        return fieldtype.strip(), None

    def mirror_field_type(self, fieldtype, mirrored):
        """The type a field takes in a mirror struct.

        Function-pointer fields come out of the JSON in a shape that is not
        valid C++; they are pointers either way, so they become void *.
        """
        base, count = self.split_array(fieldtype)
        if "(" in base:
            return "void *", count, None
        stripped = base.replace("const", "").replace("*", "").strip()
        if "*" not in base and stripped in mirrored:
            return "struct u_%s" % stripped, count, stripped
        return base, count, None

    def emit_pack_convert(self):
        """Mirror structs and converters for the Windows/macOS packing split.

        The SDK packs its structs to 4 bytes on macOS and 8 on Windows, so a
        callback the native client fills in is not the callback the Windows
        game expects to read.  Every struct therefore gets a pack-4 mirror and
        a pair of field-by-field converters, both compiled on the PE side where
        the real SDK type has the Windows layout.

        A pack-8 mirror is generated too, purely so the compiler can assert
        that steam_api.json still describes the headers this is built against.
        Nothing uses it at runtime.
        """
        entries = self.struct_fields()
        mirrored = set(entries)

        # Nested structs have to be declared before the structs that hold them.
        ordered = []
        placed = set()
        remaining = list(entries)
        while remaining:
            progress = False
            for name in list(remaining):
                deps = set()
                for field in entries[name]["fields"]:
                    _, _, nested = self.mirror_field_type(field["fieldtype"], mirrored)
                    if nested and nested != name:
                        deps.add(nested)
                if deps <= placed:
                    ordered.append(name)
                    placed.add(name)
                    remaining.remove(name)
                    progress = True
            if not progress:
                # A dependency cycle cannot happen with by-value members, but
                # fail loudly rather than emitting something that will not
                # compile.
                raise SystemExit("cycle among SDK structs: %s" % ", ".join(remaining))

        header = [BANNER.format(version=self.api.get("version", "bundled")),
                  "#ifndef STEAM_BRIDGE_PACK_CONVERT_H",
                  "#define STEAM_BRIDGE_PACK_CONVERT_H",
                  "",
                  "#include <stddef.h>",
                  ""]
        body = [BANNER.format(version=self.api.get("version", "bundled")),
                '#include "bridge_pe.h"',
                ""]

        def emit_mirror(out, prefix, pack, name):
            out.append("#pragma pack( push, %d )" % pack)
            out.append("struct %s%s" % (prefix, name))
            out.append("{")
            fields = entries[name]["fields"]
            if not fields:
                # A fieldless callback still has sizeof 1 on both sides.
                out.append("    char _empty;")
            for field in fields:
                ctype, count, nested = self.mirror_field_type(field["fieldtype"], mirrored)
                if nested:
                    ctype = "struct %s%s" % (prefix, nested)
                if count:
                    out.append("    %s %s[%s];" % (ctype, field["fieldname"], count))
                else:
                    out.append("    %s %s;" % (ctype, field["fieldname"]))
            out.append("};")
            out.append("#pragma pack( pop )")
            out.append("")

        for name in ordered:
            emit_mirror(header, "u_", 4, name)

        header.append("/* Validation only: if steam_api.json has drifted away from the")
        header.append(" * headers, these stop the build instead of corrupting data. */")
        header.append("")
        for name in ordered:
            emit_mirror(header, "w_", 8, name)
            header.append('static_assert( sizeof(struct w_%s) == sizeof(%s),' % (name, name))
            header.append('               "steam_api.json no longer describes %s" );' % name)
            for field in entries[name]["fields"]:
                if field.get("private"):
                    continue
                header.append('static_assert( offsetof(struct w_%s, %s) == offsetof(%s, %s),'
                              % (name, field["fieldname"], name, field["fieldname"]))
                header.append('               "field %s of %s moved" );' % (field["fieldname"], name))
            header.append("")

        for name in ordered:
            header.append("void steam_bridge_u2w_%s( const struct u_%s *u, %s *w );"
                          % (name, name, name))
            header.append("void steam_bridge_w2u_%s( const %s *w, struct u_%s *u );"
                          % (name, name, name))
        header.append("")

        for name in ordered:
            if name in MANUAL_CONVERTERS:
                continue
            for direction in ("u2w", "w2u"):
                if direction == "u2w":
                    body.append("void steam_bridge_u2w_%s( const struct u_%s *u, %s *w )"
                                % (name, name, name))
                    src, dst = "u", "w"
                else:
                    body.append("void steam_bridge_w2u_%s( const %s *w, struct u_%s *u )"
                                % (name, name, name))
                    src, dst = "w", "u"
                body.append("{")
                fields = entries[name]["fields"]
                if not fields:
                    body.append("    (void)u; (void)w;")
                for field in fields:
                    fname = field["fieldname"]
                    _, count, nested = self.mirror_field_type(field["fieldtype"], mirrored)
                    if nested and count:
                        body.append("    for (size_t i = 0; i < %s; i++)" % count)
                        body.append("        steam_bridge_%s_%s( &%s->%s[i], &%s->%s[i] );"
                                    % (direction, nested, src, fname, dst, fname))
                    elif nested:
                        body.append("    steam_bridge_%s_%s( &%s->%s, &%s->%s );"
                                    % (direction, nested, src, fname, dst, fname))
                    elif count:
                        body.append("    memcpy( %s->%s, %s->%s, sizeof(%s->%s) );"
                                    % (dst, fname, src, fname, dst, fname))
                    else:
                        body.append("    %s->%s = (decltype(%s->%s))%s->%s;"
                                    % (dst, fname, dst, fname, src, fname))
                body.append("}")
                body.append("")

        # Callback dispatch: manual dispatch hands back a native-layout struct
        # identified only by its callback id, so the id has to select the
        # converter and the two sizes.
        # An opaque struct has no mirror, so it has no converter either; those
        # callbacks reach the game exactly as Steam wrote them.
        callbacks = [entry for entry in self.api.get("callback_structs", [])
                     if entry.get("callback_id") and entry["struct"] in mirrored]
        skipped = [entry["struct"] for entry in self.api.get("callback_structs", [])
                   if entry.get("callback_id") and entry["struct"] not in mirrored]
        if skipped:
            print("callbacks passed through unconverted: %s" % ", ".join(sorted(skipped)))
        header.append("struct steam_bridge_callback_info")
        header.append("{")
        header.append("    int id;")
        header.append("    int native_size;")
        header.append("    int windows_size;")
        header.append("    void (*u2w)( const void *u, void *w );")
        header.append("};")
        header.append("")
        header.append("const struct steam_bridge_callback_info *steam_bridge_callback_info( int id );")
        header.append("")
        header.append("#endif /* STEAM_BRIDGE_PACK_CONVERT_H */")
        header.append("")

        for entry in callbacks:
            name = entry["struct"]
            body.append("static void steam_bridge_cb_u2w_%s( const void *u, void *w )" % name)
            body.append("{")
            body.append("    steam_bridge_u2w_%s( (const struct u_%s *)u, (%s *)w );"
                        % (name, name, name))
            body.append("}")
            body.append("")

        body.append("static const struct steam_bridge_callback_info steam_bridge_callback_table[] =")
        body.append("{")
        for entry in sorted(callbacks, key=lambda e: e["callback_id"]):
            name = entry["struct"]
            body.append("    { %d, (int)sizeof(struct u_%s), (int)sizeof(%s), steam_bridge_cb_u2w_%s },"
                        % (entry["callback_id"], name, name, name))
        body.append("};")
        body.append("")
        body.append("const struct steam_bridge_callback_info *steam_bridge_callback_info( int id )")
        body.append("{")
        body.append("    size_t count = sizeof(steam_bridge_callback_table) / sizeof(steam_bridge_callback_table[0]);")
        body.append("    for (size_t i = 0; i < count; i++)")
        body.append("        if (steam_bridge_callback_table[i].id == id) return &steam_bridge_callback_table[i];")
        body.append("    return NULL;")
        body.append("}")
        body.append("")

        self.write("pack_convert.h", "\n".join(header))
        self.write("pack_convert.cpp", "\n".join(body))
        self.mirrored = mirrored

    def write(self, name, text):
        path = os.path.join(OUT, name)
        with open(path, "w") as handle:
            handle.write(text)
        print("wrote %s (%d bytes)" % (os.path.relpath(path, REPO), len(text)))


CORE_EXPORTS = [
    "SteamAPI_Init",
    "SteamAPI_InitSafe",
    # Undecorated legacy names Valve's DLL still exports.
    "GetHSteamUser",
    "GetHSteamPipe",
    "SteamClient",
    "SteamAPI_InitAnonymousUser",
    "SteamAPI_SetBreakpadAppID",
    "SteamAPI_SetTryCatchCallbacks",
    "SteamAPI_UseBreakpadCrashHandler",
    "SteamAPI_ISteamClient_GetISteamGenericInterface",
    "SteamGameServer_GetIPCCallCount",
    "SteamAPI_Shutdown",
    "SteamAPI_RestartAppIfNecessary",
    "SteamAPI_IsSteamRunning",
    "SteamAPI_ReleaseCurrentThreadMemory",
    "SteamAPI_RunCallbacks",
    "SteamAPI_RegisterCallback",
    "SteamAPI_UnregisterCallback",
    "SteamAPI_RegisterCallResult",
    "SteamAPI_UnregisterCallResult",
    "SteamAPI_GetHSteamUser",
    "SteamAPI_GetHSteamPipe",
    "SteamAPI_GetSteamInstallPath",
    "SteamAPI_SetMiniDumpComment",
    "SteamAPI_WriteMiniDump",
    "SteamAPI_ManualDispatch_Init",
    "SteamAPI_ManualDispatch_RunFrame",
    "SteamAPI_ManualDispatch_GetNextCallback",
    "SteamAPI_ManualDispatch_FreeLastCallback",
    "SteamAPI_ManualDispatch_GetAPICallResult",
    "SteamInternal_ContextInit",
    "SteamInternal_CreateInterface",
    "SteamInternal_FindOrCreateUserInterface",
    "SteamInternal_FindOrCreateGameServerInterface",
    "SteamGameServer_InitSafe",
    "SteamGameServer_Shutdown",
    "SteamGameServer_RunCallbacks",
    "SteamGameServer_GetHSteamUser",
    "SteamGameServer_GetHSteamPipe",
    "SteamGameServer_BSecure",
    "SteamGameServer_GetSteamID",
    "SteamInternal_GameServer_Init",
    "SteamAPI_GetSteamInstallPath",
]


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_JSON
    api = load(path)
    os.makedirs(OUT, exist_ok=True)

    generator = Generator(api, header_versions(os.path.dirname(path)))
    generator.collect()
    generator.emit_iface_enum()
    # Must precede the params header: it establishes which structs have a
    # packing mirror, and the params structs are typed in terms of that.
    generator.emit_pack_convert()
    generator.emit_calls_header()
    generator.emit_pe_thunks()
    generator.emit_pe_flat()
    generator.emit_unix_thunks()
    local = generator.emit_pe_local()
    exports = generator.emit_def(CORE_EXPORTS, local)

    print("bridged %d methods across %d interfaces, %d exports"
          % (len(generator.calls), len(generator.interfaces), len(exports)))


if __name__ == "__main__":
    main()
